apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-readiness
  name: nginx-readiness
spec:
  containers:
  - image: nginx
    name: nginx-readiness
    resources: {}
    ports:
    - name: nginx-port
      containerPort: 80
      # hostPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: nginx-port
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
