apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
  - name: vol
    emptyDir: {}

  containers:
  - args:
    - /bin/sh
    - -c
    - 'sleep 3600'
    image: busybox
    name: busybox-c1
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /etc/foo

  - args:
    - /bin/sh
    - -c
    - 'sleep 3600'
    image: busybox
    name: busybox-c2
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /etc/foo

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}