---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: normal
  hostPath:
    path: /etc/foo