apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myvolume-pvc
  labels:
    name: myvolume-pvc
spec:
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi