apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: pod-nodeselector
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: In
            values:
            - nvidia-tesla-p100
  containers:  
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: pod-nodeselector
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
