apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: pi2
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - perl
        - -Mbignum=bpi
        - -wle
        - 'print bpi(2000)'
        image: perl:5.34
        name: pi
        resources: {}
      restartPolicy: Never
status: {}
