---
apiVersion: v1
data:
  var6: tuantb
  var7: tuantb2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: anotherone
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx2
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
    volumeMounts:
    - name: myvol
      mountPath: /etc/lala

  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: myvol
      configMap:
        name: anotherone

status: {}
